import { beforeEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
import component from '../GatewayHeaderAuthSettings.vue'

vi.mock('vue-i18n', async (importOriginal) => {
  const original = await importOriginal<typeof import('vue-i18n')>()
  const { default: messages } = await import('@/i18n/locales/en/admin/gatewayHeaderAuth')
  return { ...original, useI18n: () => ({ t: (key: string, params: Record<string, unknown> = {}) => {
    let value: unknown = { admin: messages, common: { loading: 'Loading', tryAgain: 'Retry', submitting: 'Saving' } }
    for (const segment of key.split('.')) value = (value as Record<string, unknown>)?.[segment]
    return String(value ?? key).replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? ''))
  } }) }
})
const api = vi.hoisted(() => ({ get: vi.fn(), update: vi.fn(), success: vi.fn() }))
vi.mock('@/api/admin/gatewayHeaderAuth', () => ({ getGatewayHeaderAuthSettings: api.get, updateGatewayHeaderAuthSettings: api.update }))
vi.mock('@/stores', () => ({ useAppStore: () => ({ showSuccess: api.success }) }))
const firstRule = () => ({ header_name: 'User-Agent', required_substring: 'XundaAI' })
const mountComponent = () => mount(component)

describe('Gateway header authentication settings', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    api.get.mockResolvedValue({ enabled: true, rules: [firstRule()] })
    api.update.mockImplementation(async data => data)
  })
  it('loads the existing rule and adds and saves multiple headers', async () => {
    const wrapper = mountComponent()
    await flushPromises()
    let rows = wrapper.findAll('[data-testid="gateway-header-rule"]')
    expect((rows[0].get('[data-field="header-name"]').element as HTMLInputElement).value).toBe('User-Agent')
    expect((rows[0].get('[data-field="required-substring"]').element as HTMLInputElement).value).toBe('XundaAI')
    expect(wrapper.text()).toContain('All rules must match')
    await wrapper.get('[data-testid="add-header-rule"]').trigger('click')
    rows = wrapper.findAll('[data-testid="gateway-header-rule"]')
    expect(rows).toHaveLength(2)
    expect(wrapper.get('[data-testid="save-header-auth"]').attributes('disabled')).toBeDefined()
    await rows[1].get('[data-field="header-name"]').setValue('X-Client-Auth')
    await rows[1].get('[data-field="required-substring"]').setValue('allowed-app')
    await wrapper.get('[data-testid="save-header-auth"]').trigger('click')
    await flushPromises()
    expect(api.update).toHaveBeenCalledWith({ enabled: true, rules: [firstRule(), { header_name: 'X-Client-Auth', required_substring: 'allowed-app' }] })
    expect(api.success).toHaveBeenCalled()
    wrapper.unmount()
  })
  it('removes the middle rule without losing other row values', async () => {
    api.get.mockResolvedValue({ enabled: true, rules: [firstRule(), { header_name: 'X-App', required_substring: 'remove-me' }, { header_name: 'X-Version', required_substring: 'v2' }] })
    const wrapper = mountComponent()
    await flushPromises()
    await wrapper.findAll('[data-testid="gateway-header-rule"]')[1].get('[data-testid="remove-header-rule"]').trigger('click')
    const rows = wrapper.findAll('[data-testid="gateway-header-rule"]')
    expect(rows).toHaveLength(2)
    expect((rows[1].get('[data-field="required-substring"]').element as HTMLInputElement).value).toBe('v2')
    await wrapper.get('[data-testid="save-header-auth"]').trigger('click')
    await flushPromises()
    expect(api.update).toHaveBeenCalledWith({ enabled: true, rules: [firstRule(), { header_name: 'X-Version', required_substring: 'v2' }] })
    wrapper.unmount()
  })
  it('requires at least one rule while enabled and supports disabling an empty rule list', async () => {
    const wrapper = mountComponent()
    await flushPromises()
    await wrapper.get('[data-testid="remove-header-rule"]').trigger('click')
    expect(wrapper.findAll('[data-testid="gateway-header-rule"]')).toHaveLength(0)
    expect(wrapper.get('[data-testid="save-header-auth"]').attributes('disabled')).toBeDefined()
    await wrapper.get('[role="switch"]').trigger('click')
    expect(wrapper.get('[data-testid="save-header-auth"]').attributes('disabled')).toBeUndefined()
    await wrapper.get('[data-testid="save-header-auth"]').trigger('click')
    await flushPromises()
    expect(api.update).toHaveBeenCalledWith({ enabled: false, rules: [] })
    wrapper.unmount()
  })
  it('disables saving invalid names or whitespace-only values in any rule', async () => {
    const wrapper = mountComponent()
    await flushPromises()
    const row = wrapper.get('[data-testid="gateway-header-rule"]')
    await row.get('[data-field="header-name"]').setValue('User Agent')
    expect(wrapper.get('[data-testid="save-header-auth"]').attributes('disabled')).toBeDefined()
    await row.get('[data-field="header-name"]').setValue('User-Agent')
    await row.get('[data-field="required-substring"]').setValue('  ')
    expect(wrapper.get('[data-testid="save-header-auth"]').attributes('disabled')).toBeDefined()
    expect(api.update).not.toHaveBeenCalled()
    wrapper.unmount()
  })
  it('bounds the number of rules', async () => {
    api.get.mockResolvedValue({ enabled: true, rules: Array.from({ length: 32 }, firstRule) })
    const wrapper = mountComponent()
    await flushPromises()
    expect(wrapper.get('[data-testid="add-header-rule"]').attributes('disabled')).toBeDefined()
    expect(wrapper.findAll('[data-testid="gateway-header-rule"]')).toHaveLength(32)
    wrapper.unmount()
  })
  it('does not allow load failures to overwrite settings with defaults', async () => {
    api.get.mockRejectedValue(new Error('offline'))
    const wrapper = mountComponent()
    await flushPromises()
    expect(wrapper.find('[role="alert"]').exists()).toBe(true)
    expect(wrapper.find('[data-testid="save-header-auth"]').exists()).toBe(false)
    expect(api.update).not.toHaveBeenCalled()
    wrapper.unmount()
  })
  it('preserves edited rules and shows failed saves without a success message', async () => {
    api.update.mockRejectedValue(new Error('save error'))
    const wrapper = mountComponent()
    await flushPromises()
    await wrapper.get('[data-testid="gateway-header-rule"] [data-field="required-substring"]').setValue('XundaAI/v2')
    await wrapper.get('[data-testid="save-header-auth"]').trigger('click')
    await flushPromises()
    expect(wrapper.find('[role="alert"]').exists()).toBe(true)
    expect((wrapper.get('[data-field="required-substring"]').element as HTMLInputElement).value).toBe('XundaAI/v2')
    expect(api.success).not.toHaveBeenCalled()
    wrapper.unmount()
  })
})
